import { Router } from "express";
import { z } from "zod";
import { Role, Cycle } from "../types/enums";
import { prisma } from "../lib/prisma";
import { authentifier, autoriserRoles } from "../middleware/auth.middleware";
export const classesRouter = Router(); classesRouter.use(authentifier);
const schemaClasse = z.object({ nom: z.string().trim().min(1).max(100), cycle: z.nativeEnum(Cycle), typeParcours: z.string().trim().max(40).nullable().optional(), niveauCode: z.string().trim().max(40).nullable().optional(), filiereCode: z.string().trim().max(40).nullable().optional(), anneeScolaireId: z.string().uuid() });

classesRouter.get("/", async (req,res)=>{ const q=req.query.anneeScolaireId; const classes=await prisma.classe.findMany({where:{ecoleId:req.utilisateur!.ecoleId,...(q?{anneeScolaireId:String(q)}:{})},include:{_count:{select:{eleves:true}},matieresClasse:{include:{matiere:true}}},orderBy:{nom:"asc"}}); res.json(classes); });
classesRouter.get("/:id", async(req,res)=>{ const c=await prisma.classe.findFirst({where:{id:req.params.id,ecoleId:req.utilisateur!.ecoleId},include:{eleves:{orderBy:[{nom:"asc"},{prenom:"asc"}]},matieresClasse:{include:{matiere:true,affectations:{include:{professeur:{select:{id:true,nom:true,prenom:true}}}}}},anneeScolaire:true}}); if(!c)return res.status(404).json({erreur:"Classe introuvable."}); res.json(c); });
classesRouter.post("/",autoriserRoles(Role.ADMIN),async(req,res)=>{const r=schemaClasse.safeParse(req.body);if(!r.success)return res.status(400).json({erreur:r.error.errors[0].message});const a=await prisma.anneeScolaire.findFirst({where:{id:r.data.anneeScolaireId,ecoleId:req.utilisateur!.ecoleId}});if(!a)return res.status(404).json({erreur:"Année scolaire introuvable."});try{const c=await prisma.classe.create({data:{...r.data,ecoleId:req.utilisateur!.ecoleId}});res.status(201).json(c)}catch{return res.status(409).json({erreur:"Cette classe existe déjà pour cette année scolaire."})}});
classesRouter.patch("/:id",autoriserRoles(Role.ADMIN),async(req,res)=>{const r=schemaClasse.partial().safeParse(req.body);if(!r.success)return res.status(400).json({erreur:r.error.errors[0].message});const c=await prisma.classe.findFirst({where:{id:req.params.id,ecoleId:req.utilisateur!.ecoleId}});if(!c)return res.status(404).json({erreur:"Classe introuvable."});if(r.data.anneeScolaireId&&!(await prisma.anneeScolaire.findFirst({where:{id:r.data.anneeScolaireId,ecoleId:req.utilisateur!.ecoleId}})))return res.status(404).json({erreur:"Année scolaire introuvable."});try{res.json(await prisma.classe.update({where:{id:c.id},data:r.data}))}catch{return res.status(409).json({erreur:"Une classe portant ce nom existe déjà."})}});
classesRouter.delete("/:id",autoriserRoles(Role.ADMIN),async(req,res)=>{const c=await prisma.classe.findFirst({where:{id:req.params.id,ecoleId:req.utilisateur!.ecoleId}});if(!c)return res.status(404).json({erreur:"Classe introuvable."});const n=await prisma.eleve.count({where:{classeId:c.id}});if(n)return res.status(409).json({erreur:"Impossible de supprimer une classe contenant encore des élèves."});await prisma.classe.delete({where:{id:c.id}});res.status(204).send()});
const schemaCoefficient=z.object({matiereId:z.string().uuid(),coefficient:z.number().positive().max(100)});
classesRouter.post("/:id/matieres",autoriserRoles(Role.ADMIN),async(req,res)=>{const r=schemaCoefficient.safeParse(req.body);if(!r.success)return res.status(400).json({erreur:r.error.errors[0].message});const c=await prisma.classe.findFirst({where:{id:req.params.id,ecoleId:req.utilisateur!.ecoleId}});const m=await prisma.matiere.findFirst({where:{id:r.data.matiereId,ecoleId:req.utilisateur!.ecoleId}});if(!c||!m)return res.status(404).json({erreur:"Classe ou matière introuvable."});const cm=await prisma.classeMatiere.upsert({where:{classeId_matiereId:{classeId:c.id,matiereId:m.id}},update:{coefficient:r.data.coefficient},create:{classeId:c.id,matiereId:m.id,coefficient:r.data.coefficient}});res.json(cm)});
classesRouter.delete("/:id/matieres/:classeMatiereId",autoriserRoles(Role.ADMIN),async(req,res)=>{const cm=await prisma.classeMatiere.findFirst({where:{id:req.params.classeMatiereId,classeId:req.params.id,classe:{ecoleId:req.utilisateur!.ecoleId}}});if(!cm)return res.status(404).json({erreur:"Association introuvable."});if(await prisma.note.count({where:{classeMatiereId:cm.id}}))return res.status(409).json({erreur:"Impossible de retirer une matière qui possède déjà des notes."});await prisma.classeMatiere.delete({where:{id:cm.id}});res.status(204).send()});
