import { Router } from "express"; import { z } from "zod"; import { Role } from "../types/enums"; import { prisma } from "../lib/prisma"; import { authentifier, autoriserRoles } from "../middleware/auth.middleware"; import { hacherMotDePasse } from "../utils/password";
export const professeursRouter=Router(); professeursRouter.use(authentifier);
const schemaCreation=z.object({nom:z.string().trim().min(1).max(100),prenom:z.string().trim().min(1).max(100),email:z.string().email(),motDePasse:z.string().min(10).max(200)});
professeursRouter.get("/",autoriserRoles(Role.ADMIN),async(req,res)=>res.json(await prisma.utilisateur.findMany({where:{ecoleId:req.utilisateur!.ecoleId,role:Role.PROFESSEUR},select:{id:true,nom:true,prenom:true,email:true,actif:true},orderBy:{nom:"asc"}})));
professeursRouter.post("/",autoriserRoles(Role.ADMIN),async(req,res)=>{const r=schemaCreation.safeParse(req.body);if(!r.success)return res.status(400).json({erreur:r.error.errors[0].message});if(await prisma.utilisateur.findUnique({where:{email:r.data.email.toLowerCase()}}))return res.status(409).json({erreur:"Cette adresse email est déjà utilisée."});const p=await prisma.utilisateur.create({data:{nom:r.data.nom,prenom:r.data.prenom,email:r.data.email.toLowerCase(),motDePasse:await hacherMotDePasse(r.data.motDePasse),role:Role.PROFESSEUR,ecoleId:req.utilisateur!.ecoleId},select:{id:true,nom:true,prenom:true,email:true,actif:true}});res.status(201).json(p)});
professeursRouter.patch("/:id",autoriserRoles(Role.ADMIN),async(req,res)=>{const r=z.object({nom:z.string().trim().min(1).max(100).optional(),prenom:z.string().trim().min(1).max(100).optional(),email:z.string().email().optional(),actif:z.boolean().optional(),motDePasse:z.string().min(10).max(200).optional()}).safeParse(req.body);if(!r.success)return res.status(400).json({erreur:r.error.errors[0].message});const p=await prisma.utilisateur.findFirst({where:{id:req.params.id,ecoleId:req.utilisateur!.ecoleId,role:Role.PROFESSEUR}});if(!p)return res.status(404).json({erreur:"Professeur introuvable."});try{const data:any={...r.data};if(data.email)data.email=data.email.toLowerCase();if(data.motDePasse){data.motDePasse=await hacherMotDePasse(data.motDePasse)}else delete data.motDePasse;delete data.email;const maj=await prisma.utilisateur.update({where:{id:p.id},data:{...data,...(r.data.email?{email:r.data.email.toLowerCase()}: {})},select:{id:true,nom:true,prenom:true,email:true,actif:true}});res.json(maj)}catch{return res.status(409).json({erreur:"Cette adresse email est déjà utilisée."})}});
professeursRouter.delete("/:id",autoriserRoles(Role.ADMIN),async(req,res)=>{const p=await prisma.utilisateur.findFirst({where:{id:req.params.id,ecoleId:req.utilisateur!.ecoleId,role:Role.PROFESSEUR}});if(!p)return res.status(404).json({erreur:"Professeur introuvable."});await prisma.utilisateur.update({where:{id:p.id},data:{actif:false}});res.status(204).send()});
const schemaA=z.object({professeurId:z.string().uuid(),classeId:z.string().uuid(),classeMatiereId:z.string().uuid()});
professeursRouter.post("/affectations",autoriserRoles(Role.ADMIN),async(req,res)=>{const r=schemaA.safeParse(req.body);if(!r.success)return res.status(400).json({erreur:r.error.errors[0].message});const [p,c,cm]=await Promise.all([prisma.utilisateur.findFirst({where:{id:r.data.professeurId,ecoleId:req.utilisateur!.ecoleId,role:Role.PROFESSEUR,actif:true}}),prisma.classe.findFirst({where:{id:r.data.classeId,ecoleId:req.utilisateur!.ecoleId}}),prisma.classeMatiere.findFirst({where:{id:r.data.classeMatiereId,classeId:r.data.classeId}})]);if(!p||!c||!cm)return res.status(404).json({erreur:"Professeur, classe ou matière introuvable."});try{res.status(201).json(await prisma.affectationProf.create({data:r.data}))}catch{return res.status(409).json({erreur:"Cette affectation existe déjà."})}});
professeursRouter.delete("/affectations/:id",autoriserRoles(Role.ADMIN),async(req,res)=>{const a=await prisma.affectationProf.findFirst({where:{id:req.params.id,classe:{ecoleId:req.utilisateur!.ecoleId}}});if(!a)return res.status(404).json({erreur:"Affectation introuvable."});await prisma.affectationProf.delete({where:{id:a.id}});res.status(204).send()});
professeursRouter.get("/mes-affectations",autoriserRoles(Role.PROFESSEUR),async(req,res)=>res.json(await prisma.affectationProf.findMany({where:{professeurId:req.utilisateur!.userId,classe:{ecoleId:req.utilisateur!.ecoleId}},include:{classe:true,classeMatiere:{include:{matiere:true}}}})));

const schemaParent=z.object({nom:z.string().trim().min(1).max(100),prenom:z.string().trim().min(1).max(100),email:z.string().email(),motDePasse:z.string().min(10).max(200)});
professeursRouter.get("/parents",autoriserRoles(Role.ADMIN),async(req,res)=>res.json(await prisma.utilisateur.findMany({where:{ecoleId:req.utilisateur!.ecoleId,role:Role.PARENT},select:{id:true,nom:true,prenom:true,email:true,actif:true,enfants:{include:{eleve:{select:{id:true,nom:true,prenom:true,matricule:true}}}}},orderBy:{nom:"asc"}})));
professeursRouter.post("/parents",autoriserRoles(Role.ADMIN),async(req,res)=>{const r=schemaParent.safeParse(req.body);if(!r.success)return res.status(400).json({erreur:r.error.errors[0].message});if(await prisma.utilisateur.findUnique({where:{email:r.data.email.toLowerCase()}}))return res.status(409).json({erreur:"Cette adresse email est déjà utilisée."});const p=await prisma.utilisateur.create({data:{...r.data,email:r.data.email.toLowerCase(),motDePasse:await hacherMotDePasse(r.data.motDePasse),role:Role.PARENT,ecoleId:req.utilisateur!.ecoleId},select:{id:true,nom:true,prenom:true,email:true,actif:true}});res.status(201).json(p)});
professeursRouter.post("/parents/:parentId/enfants/:eleveId",autoriserRoles(Role.ADMIN),async(req,res)=>{const [p,e]=await Promise.all([prisma.utilisateur.findFirst({where:{id:req.params.parentId,ecoleId:req.utilisateur!.ecoleId,role:Role.PARENT}}),prisma.eleve.findFirst({where:{id:req.params.eleveId,ecoleId:req.utilisateur!.ecoleId}})]);if(!p||!e)return res.status(404).json({erreur:"Parent ou élève introuvable."});try{res.status(201).json(await prisma.lienParentEleve.create({data:{parentId:p.id,eleveId:e.id}}))}catch{return res.status(409).json({erreur:"Cet enfant est déjà lié à ce parent."})}});
professeursRouter.delete("/parents/:parentId/enfants/:eleveId",autoriserRoles(Role.ADMIN),async(req,res)=>{await prisma.lienParentEleve.deleteMany({where:{parentId:req.params.parentId,eleveId:req.params.eleveId}});res.status(204).send()});
